### PR TITLE
Fix typos in documentation 

### PR DESCRIPTION
**Pull request by zhangchonglin**
## Purpose

_Fixes #448, #449, #450._

## Author(s)

_Chonglin Zhang, University of North Dakota_
_Stan Moore, SNL_

## Backward Compatibility

_Yes - as this is only a typo corrections in documentation_

## Implementation Notes

I am not sure about the reason to use bold font in the compute and fix variables in `adapt_grid.html` file, for example:
  - c_1 **[1]**
  - f_1 **[2]**

so I just kept the bold font style. I can change that if the bold font is not needed in the documentation.
https://github.com/sparta/sparta/blob/ddaa5f6f4f444119f5a9537a3a44729c697ce8f9/doc/adapt_grid.html#L76
https://github.com/sparta/sparta/blob/ddaa5f6f4f444119f5a9537a3a44729c697ce8f9/doc/adapt_grid.html#L192-L220

## Post Submission Checklist

_Please check the fields below as they are completed_
- [x] The feature or features in this pull request is complete
- [x] Suitable new documentation files and/or updates to the existing docs are included
- [x] One or more example input decks are included
- [x] The source code follows the SPARTA formatting

### CODE REVIEW

**Comment by stanmoore1** [comment]
@zhangchonglin nice catches, thank you very much!

**Comment by stanmoore1** [comment]
@zhangchonglin please note that the HTML files are automatically generated from the *.txt files using this tool: https://sjplimp.github.io/download.html#txt2html, https://sjplimp.github.io//docs/txt2html/README.html, so only the *.txt files should be edited directly. I added a few more fixes as a PR to your branch (can't seem to push directly). Once those are merged then this should be ready to go.

**Comment by zhangchonglin** [comment]
@stanmoore1: thanks for letting me know about the `.html` file generation process. Next time if ever find new typos, I will make sure to only modify `.txt` file. And yes, your PR to my branch is merged.

**Comment by stanmoore1** [comment]
@zhangchonglin thank you!

**Review by stanmoore1 — APPROVED** [review]

**Pull request merged**
