### PR TITLE
New compute surf torque option

### PR DESCRIPTION
**Pull request by sjplimp**
## Purpose

Add torque options to compute surf command as tx, ty, tz keywords
.
## Author(s)

Steve, with help from Darrell Robertson (NASA Ames)

## Backward Compatibility

N/A

## Implementation Notes

_Provide any relevant details about how the changes are implemented, how correctness was verified, how other features - if any - in SPARTA are affected_

## Post Submission Checklist

_Please check the fields below as they are completed_
- [ ] The feature or features in this pull request is complete
- [ ] Suitable new documentation files and/or updates to the existing docs are included
- [ ] One or more example input decks are included
- [ ] The source code follows the SPARTA formatting guidelines

## Further Information, Files, and Links

_Put any additional information here, attach relevant text or image files, and URLs to external sites (e.g. DOIs or webpages)_

### CODE REVIEW

**Comment by sjplimp** [comment]
@stanmoore1 I also want a user at NASA Ames to look this over and do a bit of testing, before we merge it.

**Comment by stanmoore1** [comment]
@sjplimp do you think we should add an example too, or it is trivial enough it isn't needed?

**Comment by sjplimp** [comment]
Probably not needed.  But maybe Darrel will have an example of computing
torque with the new command
versus post-processing of forces, which would be good to illustrate it done
both ways.

Steve

**Comment by DarrelRobertson** [comment]
Give me a couple of days. I have a pitched cube case with known solution I can include as an example done with forces on many triangles, or with the new method on far fewer.

**Comment by stanmoore1** [comment]
@DarrelRobertson any update on this PR?

**Comment by DarrelRobertson** [comment]
Sorry, should have posted here too. Yes, the torque calculation checked out fine. I also sent Steve some sample scripts and images of results.

**Comment by DarrelRobertson** [comment]
Ah, forgot to mention there were a couple of lines in compute_surf.cpp that Steve fixed. 
In compute_surf.cpp in bold in the block below, in the 3 lines arg[1+ needs replacing with arg[iarg+

  while (iarg < narg) {
    if (strcmp(arg[iarg],"norm") == 0) {
      if (iarg+2 > narg)
        error->all(FLERR,"Invalid compute surf optional keyword");
      if (strcmp(arg[iarg+1],"flow") == 0) normarea = 0;
      else if (strcmp(arg[iarg+1],"flux") == 0) normarea = 1;
      else error->all(FLERR,"Invalid compute surf optional keyword");
      iarg += 2;
    } else if (strcmp(arg[iarg],"com") == 0) {
      if (iarg+4 > narg)
        error->all(FLERR,"Invalid compute surf optional keyword");
      comflag = 1;
      **com[0] = input->numeric(FLERR,arg[1+1]);
      com[1] = input->numeric(FLERR,arg[1+2]);
      com[2] = input->numeric(FLERR,arg[1+3]);**
      iarg += 4;
    } else error->all(FLERR,"Invalid compute surf value or optional keyword");
  }

**Review by stanmoore1 — APPROVED** [review]

**Pull request merged**
