### PR TITLE
Extend mem/limit to work with acquire_ghosts_near

### PR DESCRIPTION
**Pull request by stanmoore1**
## Purpose

Extend mem/limit to work with acquire_ghosts_near

## Author(s)

Stan Moore (SNL)

## Backward Compatibility

Yes

### CODE REVIEW

**Review by sjplimp — APPROVED** [review]

**Comment by aborner1** [comment]
@stanmoore1 There is an issue with this PR (I think, it's one of the ones that were merged in the last 3-4 days, and there were several, but I believe this is the one causing the issue). Using current master https://github.com/sparta/sparta/commit/37a47711eccbb9f901a97057d9f8154ccf961515 for this.

Simulations using the "mem/limit grid" command freeze in "balance_grid".
See script below, need to run on 100 or more cores:

seed                1234
dimension           3
global              gridcut 1e-3 mem/limit grid
boundary            o o o
create_box          0.0 0.5 0.0 0.5 0.0 0.5
create_grid         10 10 10
balance_grid        rcb cell

**Comment by stanmoore1** [comment]
@aborner1 thanks for the input, I can reproduce the hang. Will take a look.

**Comment by stanmoore1** [comment]
@aborner1 Can you try out #226 and see if it fixes the issue for you?

**Comment by aborner1** [comment]
@stanmoore1 seems like it fixed it

**Pull request merged**
