### PR TITLE
Implicit

### PR DESCRIPTION
**Pull request by sjplimp**
## Purpose

Add support for 2 kinds of surface elements: explict (same as before) and implicit.
The latter are defined by grid corner point values read from a file.  Also enable
explict surfs to be distributed across procs so that models with huge surf element
counts can be modeled.  Implicit surfs are always distributed.

## Author(s)

Steve

## Backward Compatibility

N/A.

## Implementation Notes

_Provide any relevant details about how the changes are implemented, how correctness was verified, how other features - if any - in SPARTA are affected_

## Post Submission Checklist

_Please check the fields below as they are completed_
- [ ] The feature or features in this pull request is complete
- [ ] Suitable new documentation files and/or updates to the existing docs are included
- [ ] One or more example input decks are included
- [ ] The source code follows the SPARTA formatting guidelines

## Further Information, Files, and Links

_Put any additional information here, attach relevant text or image files, and URLs to external sites (e.g. DOIs or webpages)_

### CODE REVIEW

**Comment by sjplimp** [comment]
@stanmoore1 I still want to add an example or two, and a Python tool, but otherwise I think this is ready for you to look at and regress test.  It passed all my testing.  This is not fully funcational for distributed
or implicit surfs, in the sense of all SPARTA commands support them,  But I think there are error checks with messages for the commands that don't.

**Comment by stanmoore1** [comment]
@sjplimp sounds good, I'll run this through regression testing.

**Comment by sjplimp** [comment]
@stanmoore1 Also there is no checking in the Kokkos package for these kinds
of new surfs, so that should be added.

**Comment by sjplimp** [comment]
@stanmoore1 Added the Python surf generation tools and several example scripts and dirs.
Note that in examples/jagged there is a 3d sdata file that is too big to include in the distro.
See the README for how to generate it via a provided Python script.

**Comment by sjplimp** [comment]
@stanmoore1 fixed the compute reduce but with the new surf data structs

**Pull request merged**
