### PR TITLE
Surfchem heatflux

### PR DESCRIPTION
**Pull request by aborner1**
## Purpose

New feature: add an option to "compute surf" to compute the chemical energy due to catalytic surface reactions (such as exothermic recombination reactions). Also now take into account that chemical energy in the total energy,

## Author(s)

Arnaud Borner (NASA Ames)

## Backward Compatibility

Backwards compatible, except that a new surface chemistry file needs to be used,.

## Implementation Notes

Added the heat of reaction to the surface reaction input file, added "echem" as an option to "compute surf", and added the chemical surface catalytic energy to "etot". Edited doc.

## Post Submission Checklist

_Please check the fields below as they are completed_
- [X] The feature or features in this pull request is complete
- [X] Suitable new documentation files and/or updates to the existing docs are included
- [X] One or more example input decks are included
- [X] The source code follows the SPARTA formatting guidelines

### CODE REVIEW

**Comment by aborner1** [comment]
I have merged current master into this and it's passing all the reg tests. It should be ready to merge. Can we take care of it soon before it needs more manual merging?

**Comment by stanmoore1** [comment]
@aborner1 I asked @sjplimp to review.

**Comment by aborner1** [comment]
@stanmoore1 @sjplimp Ditto here: Talked to Michael and he green-lighted this. Can we proceed with review and merge?

**Comment by stanmoore1** [comment]
@aborner1 the changes here need to be ported to Kokkos, should have time to work on it this week.

**Comment by aborner1** [comment]
@stanmoore1 Have you had a chance to look at the Kokkos version of this command?

**Comment by stanmoore1** [comment]
@aborner1 I'm porting this PR to Kokkos now. Same as the other PR, if you have an example that would be helpful. Thanks

**Comment by aborner1** [comment]
@stanmoore1 Yes, I can very easily do that for this one, super simple.

**Comment by aborner1** [comment]
> @stanmoore1 Yes, I can very easily do that for this one, super simple.

done

**Comment by stanmoore1** [comment]
Thanks @aborner1!

**Comment by stanmoore1** [comment]
@aborner1 this is nearly ready to merge. One loose end I see is that the new feature only applies to the `prob` style surf reaction, `global` and `adsorb` are ignored. I think this should be mentioned in the docs.

**Comment by aborner1** [comment]
> @aborner1 this is nearly ready to merge. One loose end I see is that the new feature only applies to the `prob` style surf reaction, `global` and `adsorb` are ignored. I think this should be mentioned in the docs.

Agreed. Are you able to add a quick mention while you are working on this?

**Comment by stanmoore1** [comment]
Yes will do

**Comment by aborner1** [comment]
> @aborner1 It also looks like this is going to force all SPARTA reaction files to have 2 coefficients instead of 1, correct? It seems like it may be better to have this optional in the reaction file, i.e. default the second coeff to 0.0. @sjplimp do you agree?

That is correct, and I am fine with defaulting to a 0.0 value, which would replicate the previous behavior.

**Pull request merged**
