### PR TITLE
Allow particle species rotational DOF = 3

### PR DESCRIPTION
**Pull request by sjplimp**
## Purpose

Allow continuous rotational DOFs = 3 for complex molecular species.  Previously this was flagged as an error, awaiting a discrete rotational DOF model.  But the rest of the code appears to be fine for DOF = 3 in the continuous case.

## Author(s)

Steve

## Backward Compatibility

Should now allow models with molecular species with 3 rotational DOF to run.

## Implementation Notes

_Provide any relevant details about how the changes are implemented, how correctness was verified, how other features - if any - in SPARTA are affected_

## Post Submission Checklist

_Please check the fields below as they are completed_
- [ ] The feature or features in this pull request is complete
- [ ] Suitable new documentation files and/or updates to the existing docs are included
- [ ] One or more example input decks are included
- [ ] The source code follows the SPARTA formatting guidelines

## Further Information, Files, and Links

_Put any additional information here, attach relevant text or image files, and URLs to external sites (e.g. DOIs or webpages)_

### CODE REVIEW

**Comment by sjplimp** [comment]
@stanmoore1 This was done at Michael's request.

**Comment by stanmoore1** [comment]
@aborner1 does this fix #285?

**Review by stanmoore1 — APPROVED** [review]
No changes needed for Kokkos package.

**Comment by aborner1** [comment]
> @aborner1 does this fix #285?

This did not fix the Issue. This addresses rotational mode, my issue is with expect to vibrational modes and degeneracy.

**Pull request merged**
