### PR TITLE
add support for per-grid custom attributes

### PR DESCRIPTION
**Pull request by sjplimp**
## Purpose

Add support for custom per-grid data in the form of integer/double vectors/arrays.  Different styles can allocate and use these as needed.  Similar conceptually to custom per-particle and per-surf data.  Standardized the code for the 3 types of custom data as part of this PR.

Victoria Arias (UIUC) created an initial implementation of this feature in a SPARTA branch she is working on, but which is not yet a PR.  This portion of it is now its own PR, so that others can use this capability for developement they are doing.

## Author(s)

Victoria Arias (UIUC) and Steve Plimpton (Sandia)

## Backward Compatibility

This should only be internal to the code.  However the format of restart files changed as a result, so the per-grid and per-surf custom values can be written to/from restart files.

## Implementation Notes

_Provide any relevant details about how the changes are implemented, how correctness was verified, how other features - if any - in SPARTA are affected_

## Post Submission Checklist

_Please check the fields below as they are completed_
- [ ] The feature or features in this pull request is complete
- [ ] Suitable new documentation files and/or updates to the existing docs are included
- [ ] One or more example input decks are included
- [ ] The source code follows the SPARTA formatting guidelines

## Further Information, Files, and Links

_Put any additional information here, attach relevant text or image files, and URLs to external sites (e.g. DOIs or webpages)_

### CODE REVIEW

**Comment by sjplimp** [comment]
@stanmoore1 Can you please do a full regression test with these changes?  Also look to see if there are Kokkos changes it induces.

**Comment by stanmoore1** [comment]
@sjplimp this is giving a segmentation fault for the `examples/ambi/in.ambi` input. Other tests passed.

**Comment by sjplimp** [comment]
@stanmoore1 think I fixed it

**Comment by stanmoore1** [comment]
Re-running regression tests

**Comment by stanmoore1** [comment]
Regression tests passed.

**Comment by sjplimp** [comment]
ok - I think it is ready to merge

**Review by stanmoore1 — APPROVED** [review]

**Pull request merged**
