### PR TITLE
Surf emit momentum

### PR DESCRIPTION
**Pull request by zseckert**
## Purpose

These changes include the momentum and energy contributions of `fix emit/surf` in the results of `compute surf`. 

## Author(s)

Zak Echo, Sandia National Laboratories

## Backward Compatibility

All previous inputs should work with the new functionality, however simulations that use both `fix emit/surf` and `compute surf` on the same surface will produce different results

## Implementation Notes
These changes call `surf_tally` on all relevant computes from `fix emit/surf`. Since it is a particle creation event, `iorig` is left NULL while `ip` is the new particle, allowing all the previous logic to work for accumulating particle properties. Most of the changes in `compute surf` are to support the NULL value of `iorig`, as it previously assumed that it always existed.

I checked the problem, in parallel, with a cube that emitted different flow values from two different sides, ensuring that the forces and mass flux was correct.

## Post Submission Checklist

_Please check the fields below as they are completed_
- [x] The feature or features in this pull request is complete
- [x] Suitable new documentation files and/or updates to the existing docs are included
- [x] One or more example input decks are included
- [x] The source code follows the SPARTA formatting guidelines

### CODE REVIEW

**Comment by stanmoore1** [comment]
@zseckert @sjplimp what is the status of this PR?

**Comment by mgallis** [comment]
Ready to merge.

Michael
________________________________
From: Stan Moore ***@***.***>
Sent: Monday, August 26, 2024 3:01:23 PM
To: sparta/sparta ***@***.***>
Cc: Subscribed ***@***.***>
Subject: [EXTERNAL] Re: [sparta/sparta] Surf emit momentum (PR #502)


@zseckert<https://github.com/zseckert> @sjplimp<https://github.com/sjplimp> what is the status of this PR?

**Comment by sjplimp** [comment]
@stanmoore1 I'd like to tweak a couple things

**Comment by stanmoore1** [comment]
> @stanmoore1 I'd like to tweak a couple things

@sjplimp OK let me know when you are done.

**Comment by sjplimp** [comment]
@zseckert I made some small changes to the logic in compute_surf.cpp.  Also commented out the dump file write in the examples script (shouldn't be produced unless the user wants it).  If you have some test cases to run, it would be good to verify no answers have changed.  @stanmoore1 Otherwise ready to merge

**Comment by zseckert** [comment]
@stanmoore1 @sjplimp I ran my test and the results were consistent with the previous results. This looks good from my perspective.

**Review by stanmoore1 — APPROVED** [review]

**Pull request merged**
