### PR TITLE
Grid2paraview refinement bug

### PR DESCRIPTION
**Pull request by tjotaha**
## Purpose

Fixes bug in grid2paraview.py that created refined cells in cells that had no child cells.

## Author(s)

Tom Otahal (tjotaha@sandia.gov)

## Backward Compatibility

No issues with backwards compatibility. 

## Implementation Notes

Tested against case sent by Stan Moore. Also included a unit test to verify grid2paraview.py converts local cell ids to dashed ids correctly.

## Post Submission Checklist

_Please check the fields below as they are completed_
- [ ] The feature or features in this pull request is complete
- [ ] Suitable new documentation files and/or updates to the existing docs are included
- [ ] One or more example input decks are included
- [ ] The source code follows the SPARTA formatting guidelines

## Further Information, Files, and Links

_Put any additional information here, attach relevant text or image files, and URLs to external sites (e.g. DOIs or webpages)_

### CODE REVIEW

**Comment by stanmoore1** [comment]
@tjotaha I confirm this fixes the issue.

**Review by stanmoore1 — COMMENTED** [review]
The changes look good except the `grid.5000` file is rather large at 4.9 MB. @sjplimp does that matter?

**Comment by tjotaha** [comment]
We can remove grid.5000 if necessary. The grid.200 is enough for unit testing purposes.

**Comment by stanmoore1** [comment]
@tjotaha I think that would be good, thanks.

**Review by stanmoore1 — APPROVED** [review]

**Pull request merged**
