### PR TITLE
Arnaud added 3d marching cubes algorithm

### PR DESCRIPTION
**Pull request by sjplimp**
## Purpose

Add capabilities for 3d implicit surf elements, via a marching cubes algorithm.

## Author(s)

Steve and Arnaud

## Backward Compatibility

N/A

## Implementation Notes

_Provide any relevant details about how the changes are implemented, how correctness was verified, how other features - if any - in SPARTA are affected_

## Post Submission Checklist

_Please check the fields below as they are completed_
- [ ] The feature or features in this pull request is complete
- [ ] Suitable new documentation files and/or updates to the existing docs are included
- [ ] One or more example input decks are included
- [ ] The source code follows the SPARTA formatting guidelines

## Further Information, Files, and Links

_Put any additional information here, attach relevant text or image files, and URLs to external sites (e.g. DOIs or webpages)_

### CODE REVIEW

**Comment by sjplimp** [comment]
@stanmoore1 this is ready to regress-test and then merge, new examples were added to the examples/implicit dir

**Comment by stanmoore1** [comment]
Regression tests are running.

**Comment by stanmoore1** [comment]
All the regression tests passed.

**Comment by stanmoore1** [comment]
FYI, I'm seeing bad behavior with this PR merged in, may need another bugfix.

**Comment by aborner1** [comment]
@stanmoore1 Do you have more info about what part of the new PR is causing issues?

**Comment by stanmoore1** [comment]
I'm getting a `watertight check failed` error when using explicit non-distributed surfaces. I gave @sjplimp a reproducer.

**Comment by stanmoore1** [comment]
It must be a corner case though because the surface regression tests passed.

**Comment by aborner1** [comment]
I am under the impression the new watertight check is more robust than the old one, and picks up more errors (but it could definitely have a bug in it for explicit surfaces). This might be a stupid question, but are you sure that surface is actually watertight? It could have passed the old check yet still have some issue.

**Comment by stanmoore1** [comment]
@aborner1 not sure, need to investigate more

**Pull request merged**
