### PR TITLE
new CLL surf collision model

### PR DESCRIPTION
**Pull request by sjplimp**
## Purpose

Several new surface collision models from Krishnan Gopalan (NASA Ames).

## Author(s)

Krishnan and Arnaud Borner (NASA Ames) with some merge formating from Steve

## Backward Compatibility

N/A since new models

## Implementation Notes

_Provide any relevant details about how the changes are implemented, how correctness was verified, how other features - if any - in SPARTA are affected_

## Post Submission Checklist

_Please check the fields below as they are completed_
- [ ] The feature or features in this pull request is complete
- [ ] Suitable new documentation files and/or updates to the existing docs are included
- [ ] One or more example input decks are included
- [ ] The source code follows the SPARTA formatting guidelines

## Further Information, Files, and Links

_Put any additional information here, attach relevant text or image files, and URLs to external sites (e.g. DOIs or webpages)_

### CODE REVIEW

**Comment by sjplimp** [comment]
Krishnan - this new file does not compile b/c species[].vibtemp is no longer a scalar.
It is now a 4-vector.  So not sure how you wish to handle that in the cll() method.

**Comment by sjplimp** [comment]
Added impcll as cll/impulsive model - same issue with vibtemp scalar vs vector.

**Comment by sjplimp** [comment]
Krishnan - added the supra model.  All 4 models are now there.  Look for NOTE comments in the source code, where I had Qs.

**Comment by sjplimp** [comment]
@stanmoore1 @krishnan120492 I think this is now ready to merge into master,  Stan, there is a new examples/surf_collide, with 10 scripts.  These could be added to the regression suite.  Also, you should wait to merge until after the other surf PRs are finished, then insure there are no conflicts with this one.

**Comment by stanmoore1** [comment]
@sjplimp there is a merge conflict in doc/surf_collide.txt. Can you take a look?

**Comment by sjplimp** [comment]
@stanmoore1 Done.

**Comment by stanmoore1** [comment]
@sjplimp thanks. Regression tests are running.

**Comment by stanmoore1** [comment]
I'm seeing a compile error:

```
../surf_collide_cll.h: In member function ‘void SPARTA_NS::Surf::add_collide(int, char**)’:
../surf.cpp:1879:44: error: invalid new-expression of abstract class type ‘SPARTA_NS::SurfCollideCLL’
         sc[nsc] = new Class(sparta,narg,arg); \
                                            ^
../surf_collide_cll.h:17:1: note: in expansion of macro ‘SurfCollideStyle’
 SurfCollideStyle(cll,SurfCollideCLL)
 ^~~~~~~~~~~~~~~~
In file included from ../style_surf_collide.h:1:0,
                 from ../surf.cpp:17:
../surf_collide_cll.h:29:7: note:   because the following virtual functions are pure within ‘SPARTA_NS::SurfCollideCLL’:
 class SurfCollideCLL : public SurfCollide {
       ^~~~~~~~~~~~~~
```

**Comment by sjplimp** [comment]
Just fixed this ...

Thanks,
Steve

**Pull request merged**
