### PR TITLE
Read write surfs

### PR DESCRIPTION
**Pull request by sjplimp**
## Purpose

Extend the read_surf, write_surf, and read_isurf commands to work with explicit, distributed, and implicit surfaces.  The surface data file now has 2 formats, with and without a Points section.  If the section is not included, individual point coords are listed with the line and surface elements.  Lines and Triangles now have a unique ID.  The lines and triangles do not need to be listed in order, which will typically be the case in a file written when surface elements are distributed.

## Author(s)

Steve

## Backward Compatibility

The original format for surface files should still work.

## Implementation Notes

_Provide any relevant details about how the changes are implemented, how correctness was verified, how other features - if any - in SPARTA are affected_

## Post Submission Checklist

_Please check the fields below as they are completed_
- [ ] The feature or features in this pull request is complete
- [ ] Suitable new documentation files and/or updates to the existing docs are included
- [ ] One or more example input decks are included
- [ ] The source code follows the SPARTA formatting guidelines

## Further Information, Files, and Links

_Put any additional information here, attach relevant text or image files, and URLs to external sites (e.g. DOIs or webpages)_

### CODE REVIEW

**Comment by sjplimp** [comment]
@stanmoore1 do not merge this PR yes.  Arnaud will do some testing.

**Comment by aborner1** [comment]
@sjplimp @stanmoore1 All good from my side

**Comment by sjplimp** [comment]
@stanmoore1 and @aboner1 I think this PR is now complete.  For explicit surfs (and writing of implicit surfs via the write_surf command, either when reading vis read_isurf, or independetly), you can now use parallel files for both reeading and writing.  This should speed-up I/O for large data sets.  Arnaud, please test on any big systems and on large #s of procs.  Stan, you should regress test all of this, since you have tests I don't.  But I think this is basically ready to merge.

**Comment by stanmoore1** [comment]
@sjplimp I'm seeing a compile error with the KOKKOS package. Will look into this.

**Comment by sjplimp** [comment]
@stanmoore1 Most recent push has changes to compute surf and fix ave surf which may impact Kokkos versions.

**Comment by stanmoore1** [comment]
@sjplimp this now compiles and runs. The regular SPARTA (non-Kokkos) regression tests pass, but some of the Kokkos regression tests are failing. Working on this...

**Comment by stanmoore1** [comment]
Kokkos CPU works now, but a few regression tests are still failing with CUDA on GPUs.

**Pull request merged**
