### PR TITLE
Fix reread surf custom dat

### LINKED ISSUE #496: Incorrect custom surf values when removing and rereading a surface
## Summary

When surfaces are read and removed the custom data gets out of sync.

## Type of Issue

Bug report

## Detailed Description (Enhancement Suggestion)

I was trying to implement a time and space varying BC with the new surf/emit functionality brought in in #491. Essentially I generated a bunch of surf files that had identical points/tris, but different custom vectors. Then, in a loop, I would call run for a few dozen timesteps, remove the surf, and read in the next surf. However, I noticed that the emission wasn't changing in time and verified through write_surf commands that the custom data for surfs does not change when reread.

I tried to reproduce this using the custom/in.custom.cube.read example and found that the below reproduction has the right behavior (for write_surf) when using explicit/distributed surfaces, but write_surf is incorrect when using an explicit surface. However, in both cases it appears that the surf/emit with custom values is always incorrect.

## SPARTA Version (Bug Report)

This was on the branch fix-emit-surf-enhance that was just merged via #491. It has been reproduced on master (ebce4368)

## Steps to Reproduce (Bug Report)

Using the custom/in.custom.cube.read input I made a copy of data.cube.custom and incremented the first custom column on the triangles by 1 (10 -> 11, 20 -> 21, etc). 

I updated the input deck, adding `group 1` to the read_surf command then added the following directly after it:

```
read_surf           data.cube.custom &    
                    custom ivec int 0 &    
                    custom iarray int 2 &    
                    custom dvec float 0 &    
                    custom darray float 3 &    
                    trans 4.5 4.5 4.5 origin 5 5 5 &    
                    scale 3 3 3 rotate 45 1 1 1  &
                    group 1

write_surf data.cube.out.1 custom ivec
remove_surf 1

read_surf           data.cube.custom2 &    
                    custom ivec int 0 &    
                    custom iarray int 2 &    
                    custom dvec float 0 &    
                    custom darray float 3 &    
                    trans 4.5 4.5 4.5 origin 5 5 5 &    
                    scale 3 3 3 rotate 45 1 1 1  &
                    group 1

write_surf data.cube.out.2 custom ivec
```
I also changed from `global surfs explicit/distributed` to `global surfs explicit` (distributed surfs appear to work for write_surf, but not emit/surf).

## Expected Behavior (Bug Report)

The custom ivec in `data.cube.out.2` should match that in `data.cube.custom2`.

## Actual Behavior (Bug Report)

The custom ivec in `data.cube.out.2` instead matches `data.cube.custom`.

## Further Information, Files, and Links

_Put any additional information here, attach relevant text or image files and URLs to external sites, e.g. relevant publications_

### PR DESCRIPTION
**Pull request by zseckert**
## Purpose
This branch fixes an error with custom surface values when multiple surface files are read, or surfaces are read, removed, then reread with different data.

fixes #496 

## Author(s)

Zak Echo

## Backward Compatibility

No changes to inputs

## Implementation Notes

`surf->estatus` was left at a value of 1 when more surfaces were read. This meant that custom values were not respread to other processes in `eivec_local` and were just left in `eivec` (or the array/vec int/double equivalents).

## Post Submission Checklist

_Please check the fields below as they are completed_
- [x] The feature or features in this pull request is complete
- [x] Suitable new documentation files and/or updates to the existing docs are included
- [x] One or more example input decks are included
- [x] The source code follows the SPARTA formatting guidelines

## Further Information, Files, and Links

_Put any additional information here, attach relevant text or image files, and URLs to external sites (e.g. DOIs or webpages)_

### CODE REVIEW

**Comment by zseckert** [comment]
I still want to test that this works for the new emit/surf with flow values from custom before it is merged.

**Comment by zseckert** [comment]
I tested that the reread of surfaces properly affects the emit/surf capability, using an example where a cube emitted from one surface for a few hundred time steps, then rereading a surf and emitting from a different face for a few hundred more time steps. If you feel this is worth capturing as an additional example/test, just let me know and I'll set it up.

I'm working on a fix for the parallel version of custom/in.custom.cube.reread, and once that is done I think this will be ready for someone to take a look at.

**Comment by stanmoore1** [comment]
>I'm working on a fix for the parallel version of custom/in.custom.cube.reread, and once that is done I think this will be ready for someone to take a look at.

@zseckert sounds good, let me know when you are done

**Comment by zseckert** [comment]
@stanmoore1 I think with my last commit I got everything working (it was an issue with the expectation of the test harness for a test that didn't actually call `run`, not an actual bug in the code). I think this is ready for a review.

**Review by stanmoore1 — APPROVED** [review]

**Pull request merged**
