### PR TITLE
More general external fields

### PR DESCRIPTION
**Pull request by sjplimp**
## Purpose

Change the global gravity command to global field and allow 3 variants.  One for constant (same as gravity was), one for per-particle fields, one for per grid cell fields.  The latter two can be encoded by particle-style or grid-style variables which allow for spatially- and time-varying fields.  This PR only adds support for per-particle fields. Per-grid cell fields will be in a later PR.
A new fix field/particle is added to use with the global field particle command.  Also a species_modify command is added which allows setting of the magnetic moement of any particle species.  This PR thus enables an external magnetic field to affect particle motion.

## Author(s)

Steve

## Backward Compatibility

Previous use of the global gravity ... command will now need to be global field constant ...

## Implementation Notes

_Provide any relevant details about how the changes are implemented, how correctness was verified, how other features - if any - in SPARTA are affected_

## Post Submission Checklist

_Please check the fields below as they are completed_
- [ ] The feature or features in this pull request is complete
- [ ] Suitable new documentation files and/or updates to the existing docs are included
- [ ] One or more example input decks are included
- [ ] The source code follows the SPARTA formatting guidelines

## Further Information, Files, and Links

_Put any additional information here, attach relevant text or image files, and URLs to external sites (e.g. DOIs or webpages)_

### CODE REVIEW

**Comment by sjplimp** [comment]
@stanmoore1 - I think this initial version of a generalized external field acting on particle advection is ready to go.

**Comment by sjplimp** [comment]
@stanmoore1 resolved the merge conflict

**Comment by sjplimp** [comment]
@stanmoore1 ok - good to go

**Comment by stanmoore1** [comment]
This needs changes for the Kokkos package.

**Review by stanmoore1 — APPROVED** [review]

**Pull request merged**
