### PR TITLE
Ambipolar recombination with one or multiple groups

### PR DESCRIPTION
**Pull request by sjplimp**
## Purpose

Refactoring of how multi-group collisions are performed.  Also enabling of recombination reactions with ambipolar models.

## Author(s)

Steve

## Backward Compatibility

Should be backward compatible, but multi-group logic for non-ambipolar models also changed.

## Implementation Notes

Michael has some test scripts that will be added to the examples folder when this PR is complete.

## Post Submission Checklist

_Please check the fields below as they are completed_
- [ ] The feature or features in this pull request is complete
- [ ] Suitable new documentation files and/or updates to the existing docs are included
- [ ] One or more example input decks are included
- [ ] The source code follows the SPARTA formatting guidelines

## Further Information, Files, and Links

_Put any additional information here, attach relevant text or image files, and URLs to external sites (e.g. DOIs or webpages)_

### CODE REVIEW

**Comment by sjplimp** [comment]
@stanmoore1 This is ready for final testing and merge

**Comment by stanmoore1** [comment]
OK I'm running this PR through the regression tests now.

**Comment by stanmoore1** [comment]
@sjplimp the `ambi` test is failing, was this PR supposed to change that?

**Comment by sjplimp** [comment]
@stanmoore1 By failing do you just mean different answers?  I think this PR could have altered
results in a statistical sense, so you can likely just re-bless the new answers.  Please check
with Michael to verify.

**Comment by stanmoore1** [comment]
This is good to go wrt Kokkos.

**Pull request merged**
