### PR TITLE
Added requirement for cpp11

### PR DESCRIPTION
**Pull request by andrewykhong**
## Purpose

Compilers require cpp11 support. This is a prerequisite for PR #461 

## Author(s)

Andrew Y. K.  Hong, Stan Moore

## Backward Compatibility

None to my knowledge

## Implementation Notes

Added compiler flags to makefiles

## Post Submission Checklist

_Please check the fields below as they are completed_
- [ ] The feature or features in this pull request is complete
- [ ] Suitable new documentation files and/or updates to the existing docs are included
- [ ] One or more example input decks are included
- [x] The source code follows the SPARTA formatting guidelines

## Further Information, Files, and Links

No inputs or documentation for this PR

### CODE REVIEW

**Comment by andrewykhong** [comment]
@stanmoore1 I changed the Makefiles, but what needs to be changed for cmake? I'm not familiar with cmake

**Comment by stanmoore1** [comment]
@andrewykhong I've having a really hard time finding a compiler old enough that doesn't support C++11 to test this PR...

**Comment by andrewykhong** [comment]
@stanmoore1 I added the "math" files which i need for a different pull request. in the past, I have tried to call the make mpi without the c++11 flag and it failed to compile for me. The mpi module I am using is mpi/openmpi-x86_64. Not sure if this is helpful

**Comment by stanmoore1** [comment]
@andrewykhong not sure if we can copy files from LAMMPS wholesale into SPARTA, especially since it was written by an external collaborator and not one of us. I need to ask @sjplimp what he thinks.

**Comment by andrewykhong** [comment]
@stanmoore1 that's good to know. Is there anything else that needs to be changed for this PR?

**Comment by stanmoore1** [comment]
> @stanmoore1 that's good to know. Is there anything else that needs to be changed for this PR?

We need to add a note to the doc page about the compiler requiring C++11 support.

**Comment by andrewykhong** [comment]
Added note in documentation about C++11 requirement (and C++17 requirement for Kokkos) in "Making SPARTA" section under the subsection "Read this first".

**Comment by stanmoore1** [comment]
@andrewykhong I checked the Math Eigen library licenses and talked to one of the LAMMPS developers and I believe it is permissible to include the files in SPARTA.

**Comment by stanmoore1** [comment]
@andrewykhong do we need the `Lanczos` part, or only the `Jacobi` part of the Eigen library? I.e. can we delete out the Lanczos code?

**Comment by andrewykhong** [comment]
@stanmoore1 SWPM does not need Lanczos (PR #461). I don't think we need it since that library is not used anywhere else that I know of

**Review by stanmoore1 — APPROVED** [review]
Andrew Jewett is fine with us using his Eigen Jacobi code.

**Pull request merged**
