### PR TITLE
New version of surf2grid persurf algorithm

### PR DESCRIPTION
**Pull request by sjplimp**
## Purpose

Replace the surf2grid mapping algorithm (persurf variant) with a new one that should scale better.

## Author(s)

Steve

## Backward Compatibility

Both algorithms (percell and persurf) should give the same answers.  Which is faster depends on the problem.

## Implementation Notes

_Provide any relevant details about how the changes are implemented, how correctness was verified, how other features - if any - in SPARTA are affected_

## Post Submission Checklist

_Please check the fields below as they are completed_
- [ ] The feature or features in this pull request is complete
- [ ] Suitable new documentation files and/or updates to the existing docs are included
- [ ] One or more example input decks are included
- [ ] The source code follows the SPARTA formatting guidelines

## Further Information, Files, and Links

_Put any additional information here, attach relevant text or image files, and URLs to external sites (e.g. DOIs or webpages)_

### CODE REVIEW

**Comment by sjplimp** [comment]
@stanmoore1 Arnaud is going to test this on various problems, to check for bugs and perf.  If all goes well, then we can merge.  But you can do also do regression testing now.

**Comment by aborner1** [comment]
Can this PR be used directly with the master, rather than going through surf-tweaks?

**Comment by sjplimp** [comment]
Not sure what you mean.  This PR was branched from current master, so it does not include any code from other current PRs, e.g. surf-tweaks.

**Comment by aborner1** [comment]
@sjplimp Understood.

**Comment by stanmoore1** [comment]
I'm running regression tests now.

**Comment by stanmoore1** [comment]
Some heavy regression tests are running slow, one seems to be hanging, need to dig in more.

**Comment by stanmoore1** [comment]
There seems to be a problem with this PR--for some cases it widens the gap
between current master and the old persurf algorithm using parent cells.

**Comment by stanmoore1** [comment]
Closing #231, which was superseded by #241.

**Pull request closed without merging**
