### PR TITLE
Rotrel equilibrium fix

### LINKED ISSUE #2: Variable Rotational Relaxation
## Summary

Current variable rotational relaxation approach does not reproduce the expected relaxation rate.

## Type of Issue

Physics Bug

## Detailed Description

The current version of the rotational relaxation model does not correctly reproduce the expected relaxation rate and will not reach equilibrium. In the current model, the energy of the colliding particles is used in Parker's model to calculate Z_rot, `rotphi` in the code. Using `Ec` to calculate Z_rot requires a correction factor that Boyd developed in the past. This is quickly summarized in Boyd and Schwartzentruber, _Nonequilibrium Gas Dynamics and Molecular Simulation_, pp. 254-5. 

I typically prefer using the cell temperature approach where `Tr` is replaced with the cell temperature. I suggest using the cell translational temperature instead of calculating a composite cell temperature. This is also the approach taken by Boyd and Schwartzentruber, pp. 253-4.   

The vibrational relaxation number, Z_vib or `vibphi` in the code, may also suffer from the same issue. Boyd and Schwartzentruber, pp. 260-5 discusses vibrational relaxation. In my code, I assume the translational temperature for the Millikan-White model.

## SPARTA Version

`collide_vss.cpp`

Rotation:
https://github.com/sparta/sparta/blob/45e17cdbda3845e40ed5aaf44399323c365b2941/src/collide_vss.cpp#L773

Vibration:
https://github.com/sparta/sparta/blob/45e17cdbda3845e40ed5aaf44399323c365b2941/src/collide_vss.cpp#L785

## Expected Behavior

Thermal equilibrium should be obtained in a relaxation case.

## Actual Behavior

When initializing a simple heat bath simulation at equilibrium, the temperatures diverge to some steady nonequilibrium state when using variable rotational relaxation. The correct result is observed when using a constant relaxation number.

## Steps to Reproduce

Run a heat bath simulation with N2 where all temperatures start at an equilibrium of ~10,000 K.

### PR DESCRIPTION
**Pull request by zseckert**
## Purpose

These changes address the variable rotational portion of #187.

It was brought to our attention by Maninder Grover and Dr. Paolo Valentini that including the rotational energy of the relaxing particle in the call to rotrel resolved the issue with temperature varying rotational relaxation not maintaining equilibrium at steady state.

Eq (3.32) in Bird 2013 discusses the same inclusion, with the added detail of including the rotational DoF in the calculation for T_coll. There are discussions of shortcomings of this approach related to partially excited modes, but we feel the steady state equilibrium issue is much more significant.

Further analysis is being performed to understand exactly why the non-equilibrium is not maintained with the original implementation and to hopefully provide insights to fixes of the issues with the current implementation discussed by Bird.

## Backward Compatibility

This will change the results of simulations including temperature varying rotational relaxation

## Implementation Notes

This does deviate from the original Parker (1959) derivation of the temperature dependence of Zrot, but our tests examining both the relaxation rate and the rotational energy distribution function show no significant deviations from what is expected.

## Post Submission Checklist

_Please check the fields below as they are completed_
- [x] The feature or features in this pull request is complete
- [x] Suitable new documentation files and/or updates to the existing docs are included
- [x] One or more example input decks are included
- [x] The source code follows the SPARTA formatting guidelines

There is currently not an example that uses variable relaxation, but I can add one based on collide if desired.

Fixes #2.

### CODE REVIEW

**Comment by stanmoore1** [comment]
@zseckert thanks, I will update the Kokkos version.

**Review by stanmoore1 — APPROVED** [review]

**Comment by stanmoore1** [comment]
>There is currently not an example that uses variable relaxation, but I can add one based on collide if desired.

@zseckert This would be very good, if possible. All the regression tests passed, which confirms this case isn't covered in our test suite.

**Comment by zseckert** [comment]
> @zseckert This would be very good, if possible. All the regression tests passed, which confirms this case isn't covered in our test suite.

Okay, I will do so. Is there a way to run the regression tests locally? It looks from the results that it is CTest based, so is using the CMake build sufficient?

**Comment by stanmoore1** [comment]
Yes the tests use CTest, instructions are here: https://sparta.github.io/doc/Section_start.html#start_5.

**Comment by zseckert** [comment]
I have added two tests. The first is for constant Zr that equilibrates to the expected 6040 K for both T_tr and T_r.  The second uses variable Zr, and without the fix, T_r equilibrates about 200 K below T_tr. With the fix, they are within a couple K of the expected.

Both examples are on 3x3x3 grids to avoid the single cell/serial bug of equilibrium not being reached, but they run fast enough on 1 cell/1 core (about 90 s) that once that fix is complete, the constant Zr problem could also act as regression for that (It currently has about 200 K non-equilibrium when run in 1 cell).

**Comment by zhangchonglin** [comment]
@zseckert: I think this is more of an issue with regard to equipartition of energy between different energy modes, when using the Borgnakke–Larsen model to sample the post-collision energy. Usually the relaxation rate was not affected much. Simply speaking, within the Borgnakke-Larsen model framework and using energy dependent collision probability for inelastic collision (in this case the Parker model), we want to sample a `"biased"' energy distribution function (the energy distribution from all molecules selected for inelastic collision), to ensure equipartition of energy modes.

This issue was first discussed and resolved by Abe in his RGD paper: `“Direct Simulation Monte Carlo Method for Internal- Translational Energy Exchange in Nonequilibrium Flow,” Rarefied Gas Dynamics: Theory and Simulations; Proceedings of the 18th International Symposium on Rarefied Gas Dynamics, Univ. of British Columbia, Vancouver, BC, Canada, 1994, pp. 103–113`. Since this is some implementation details that is usually overlooked, I had some discussions of this in our AIAA journal paper: Nonequilibrium-Direction-Dependent Rotational Energy Model for Use in Continuum and Stochastic Molecular Simulation. Kosyanchuk and Yakunchikov also have some excellent discussions of this in their recent Physics of Fluids paper, from a different perspective: `A detailed multiscale study of rotational–translational relaxation process of diatomic molecules`.

**Comment by stanmoore1** [comment]
Thanks @zseckert. I'm going to run the example scripts in #187 and #2 to see if the equilibrium issues are now resolved.

**Comment by mgallis** [comment]
You may want to use the new RNG Stan implemented.

Michael

On Jun 25, 2021, at 7:58 AM, Stan Moore ***@***.***> wrote:

﻿

Thanks @zseckert<https://github.com/zseckert>. I'm going to run the example scripts in #187<https://github.com/sparta/sparta/issues/187> and #2<https://github.com/sparta/sparta/issues/2> to see if the equilibrium issues are now resolved.

**Comment by stanmoore1** [comment]
This does indeed fix #2.

**Comment by stanmoore1** [comment]
I also confirm this fixes the issue shown by the input script in #187.

**Comment by stanmoore1** [comment]
To clarify, this fixes the variable rotational portion of #187 as @zseckert mentioned in the description. Using `vibrate discrete` in the input in #187 still gives vibrational nonequilibrium.

**Review by sjplimp — APPROVED** [review]

**Pull request merged**
