### PR TITLE
Add CTest and CDash support

### PR DESCRIPTION
**Pull request by e10harvey**
##  Purpose

This PR enables testing of existing `examples` directories via CTest and includes one CMake build system fix in fdd679d4e60fb1c45e6dce12fb58fe7123f18768.

These changes add support for the following new CMake options:
* SPARTA_ENABLE_TESTING
  * Add tests in examples to be run via ctest.
* SPARTA_DSMC_TESTING_PATH
  * Add tests in SPARTA_DSMC_TESTING_PATH/examples to be run via ctest.
  * Run all tests via SPARTA_DSMC_TESTING_PATH/regression.py.
* SPARTA_SPA_ARGS
  * Additional arguments for the sparta binary. Only applied if SPARTA_ENABLE_TESTING or
  SPARTA_DSMC_TESTING_PATH are enabled.
* SPARTA_DSMC_TESTING_DRIVER_ARGS
  * Additional arguments for SPARTA_DSMC_TESTING_PATH/regression.py.
* SPARTA_CTEST_CONFIGS
  * Additional ctest configurations, separated by `;`, that allow `SPARTA_SPA_ARGS_<CONFIG_NAME>` or `SPARTA_DSMC_TESTING_DRIVER_ARGS_<CONFIG_NAME>` to be specified.
* SPARTA_MULTIBUILD_CONFIGS
  * Additional build configurations, separated by `;`, that build sparta with the cache file from `SPARTA_MULTIBUILD_PRESET_DIR/<CONFIG_NAME>.cmake`.
* SPARTA_MULTIBUILD_PRESET_DIR
  * The path to custom preset files when using `SPARTA_MULTIBUILD_CONFIGS`. Only applied if `SPARTA_MULTIBUILD_CONFIGS` is enabled.

## Author(s)

Evan Harvey, Sandia National Labs

## Backward Compatibility

All changes are backwards compatible.

## Implementation Notes

Correctness was verified by testing on my laptop and via SPARTA's CI/CD pipelines. Please see `BUILD_CMAKE.md` for more implementation details.

## Post Submission Checklist

_Please check the fields below as they are completed_
- [x] The feature or features in this pull request is complete
- [x] Suitable new documentation files and/or updates to the existing docs are included
- [x] One or more example input decks are included
- [x] The source code follows the SPARTA formatting guidelines

@stanmoore1

### CODE REVIEW

**Comment by e10harvey** [comment]
> @e10harvey should we describe in the SPARTA docs how to enable the tests as well, or is this an intermediate PR?

@stanmoore1, This is not an intermediate PR. I will update the SPARTA docs.

**Comment by stanmoore1** [comment]
@e10harvey This looks good, I just had two small comments on the docs.

**Comment by stanmoore1** [comment]
@e10harvey it looks like some of the examples accidentally got renamed, can you revert that?

**Comment by e10harvey** [comment]
> @e10harvey it looks like some of the examples accidentally got renamed, can you revert that?

@stanmoore1, certainly. Are you referring to:
- `examples/ablation/in.ablation.3d.reactions → examples/ablation/FAILING.in.ablation.3d.reactions`
- `examples/jagged/in.jagged.3d → examples/jagged/DISABLED.in.jagged.3d`
- `examples/jagged/in.jagged.3d.distributed → examples/jagged/DISABLED.in.jagged.3d.distributed`?

**Comment by stanmoore1** [comment]
Yes, those 3 examples

**Pull request merged**
