### PR TITLE
Create particles cut

### PR DESCRIPTION
**Pull request by sjplimp**
## Purpose

Enable the create_particles command to insert particles in cut and split cells which are overlapped by surface elements.  Previously create_particles skipped those cells.  There is now a "cut yes/no" optional keyword.  The default is "yes", If set to "no",
then the behavior should be identical to the old behavior.

## Author(s)

Steve

## Backward Compatibility

If a system has surfaces and create_particles is used, the set of inserted particles will now be different, unless the
"cut no" option is used.

## Implementation Notes

This needs full regression testing and some regression references may need to be updated for the new behavior.

## Post Submission Checklist

_Please check the fields below as they are completed_
- [ ] The feature or features in this pull request is complete
- [ ] Suitable new documentation files and/or updates to the existing docs are included
- [ ] One or more example input decks are included
- [ ] The source code follows the SPARTA formatting guidelines

## Further Information, Files, and Links

_Put any additional information here, attach relevant text or image files, and URLs to external sites (e.g. DOIs or webpages)_

### CODE REVIEW

**Comment by sjplimp** [comment]
@stanmoore1 This should be run thru the full set of regression tests.  I will send you an email about the Kokkos version of create_particles.

**Comment by stanmoore1** [comment]
@sjplimp should I use the `cut no` option for regression testing, or update all the tests to `cut yes`?

**Comment by sjplimp** [comment]
@stanmoore1 If it's not too much bother could you do both?   First regress test with "cut no", make sure
nothing changed.  Then update all the regression gold standars with "cut yes" (default for new version of create_particles)

**Comment by stanmoore1** [comment]
I'm seeing a regression with `twopass` and `cut no` (old behavior).

**Comment by stanmoore1** [comment]
This PR changes the order of the pRNG in create_particles, so it will change results for both `cut yes` and `cut no`.

**Comment by stanmoore1** [comment]
If I restore the order of the pRNG, then the regression tests pass for `cut no`. Will test `cut yes` now to make sure nothing crashes, then rebless all the tests when this is merged.

**Comment by stanmoore1** [comment]
I'm seeing some issues with the regression tests, need to investigate more.

**Comment by stanmoore1** [comment]
No new issues discovered, this is ready to merge. It will break many regression tests, will rebless.

**Pull request merged**
