### PR TITLE
Added Argon shock tube example 

### PR DESCRIPTION
**Pull request by marisapetrusky**
## Purpose

Adds a shock tube example to SPARTA's testing suite.

## Author(s)

Jenny Horing, University of Colorado Boulder.
Marisa Petrusky, University of Colorado Boulder.

## Implementation Notes

Utilizes region command and two identical versions of the species Argon to initialize each half of the shock tube. 

Verified with analytical shock tube relations. 

## Post Submission Checklist

_Please check the fields below as they are completed_
- [X] The feature or features in this pull request is complete
- [ ] Suitable new documentation files and/or updates to the existing docs are included
- [X] One or more example input decks are included
- [X] The source code follows the SPARTA formatting guidelines

### CODE REVIEW

**Comment by marisapetrusky** [comment]
The chosen gas was Argon to avoid any internal energy modes, and the domain is small enough to where the problem only takes a couple minutes to run. We made use of the region command to create two density zones. Let us know if we are missing anything to make a complete example!

For visualization purposes, we created two copies of the Argon species so a movie would show the high density gas (red) expanding into the low density gas (green). However, a cleaner way to do this might be to color particles based on mixture species or region initialization. Is there a way of doing that? 

Additionally, the particles seem to appear on top of the simulation domain outline, which is something I do not see in the other Pictures/Documentation for the other examples. Is there a command that can force the box to appear over the particles? If there are any other ideas on how to make the image better, please let us know as well.

**Comment by zhangchonglin** [comment]
> For visualization purposes, we created two copies of the Argon species so a movie would show the high density gas (red) expanding into the low density gas (green). However, a cleaner way to do this might be to color particles based on mixture species or region initialization. Is there a way of doing that? 

The manual page of [`dump image`](https://sparta.github.io/doc/dump_image.html
) command might have the command/keyword you want to color particles differently, look specifically for `Rendering of particles` section. 


>  Is there a command that can force the box to appear over the particles?

The [dump image](https://sparta.github.io/doc/dump_image.html) manual page has the following option to allow the box to show up; you could search to find the keyword pairs:
```
  box values = yes/no diam = draw outline of simulation box
    yes/no = do or do not draw simulation box lines
    diam = diameter of box lines as fraction of shortest box length
```

**Comment by stanmoore1** [comment]
@marisapetrusky this is looking great. Small change request: can you please enable the `twopass` option for the `create_particles` command (for example see https://github.com/sparta/sparta/blob/master/examples/collide/in.collide#L30), and also add a header comment at the top, similar to this: https://github.com/sparta/sparta/blob/master/examples/collide/in.collide#L1-L9. Then update the log files since this will change the numerics, and it should be good to go. After that, I'll enable this example to run as part of the Github pull request tests and our internal regression testing.

**Comment by marisapetrusky** [comment]
Thank you for the suggestions! Mixture or initial region do not appear to be particle attributes, so I think keeping the coloring as is will work best in order to avoid altering SPARTA's particle class structure. 

Looking more closely at some of SPARTA's other visualizations (specifically [Chemistry](https://sparta.github.io/movies/chem.gif)), it seems like the particles sitting on top of the box outline is to be expected for a wall boundary. I added the command `box yes` anyway. 

The `in` file has been updated along with the log files for enabling the `twopass` option. 

We would love to have the visualization added! We have the gif and images on hand, should we send them here, via email, etc?

**Comment by stanmoore1** [comment]
@marisapetrusky @jhoring89 apologies for the long delay (I haven't worked on SPARTA for a while).

I had a few small tweaks to this pull request, but couldn't push the changes directly to your branch for some reason. So I submitted a pull request here: https://github.com/marisapetrusky/shock-tube-example/pull/1. Once that is merged, this should be ready to go. 

I can also put the movie on the SPARTA website--you can either post a mp4 or zip file here, or my email is listed here: https://sparta.github.io/authors.html.

Thanks!

**Review by stanmoore1 — APPROVED** [review]

**Comment by marisapetrusky** [comment]
No worries! Here is an mp4 file of the shock tube. Thanks so much for working with us on this!

https://user-images.githubusercontent.com/39495297/217049647-2d56d253-3e76-4d95-a931-b2d71cd76d66.mp4

**Comment by stanmoore1** [comment]
@marisapetrusky thanks, I'll add that to the website. The shock tube example is now part of SPARTA internal regression testing:

```
14:32:24 ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
14:32:24 dir = dsmc_testing/examples/shock_tube
14:32:24 test = shocktube
14:34:36 10000
14:34:36 read 101 log entries
14:34:36 10000
14:34:36 read 101 log entries
14:34:36 ==== generating gold standard for test shocktube ====
14:34:36 ==== comparing log.mpi_4.shocktube with log.archive.06Feb23.linux.mpi_4.shocktube ====
14:34:36 Step     error  0.0 wrt norm 10000.0
14:34:36 Np       error  0.0 wrt norm 11249.0
14:34:36 Natt     error  0.0 wrt norm 38292.0
14:34:36 Ncoll    error  0.0 wrt norm 20991.0
14:34:36 Nscoll            error  0.0
14:34:36 Nscheck           error  0.0
14:34:36 
14:34:36 All rows are identical
14:34:36 *** test shocktube passed
14:34:36 elapsed time = 132.219048023 s for test shocktube
14:34:36 ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
14:34:36 
```

As well as Github pull request testing:
```
61/126 Test #125: mpi.in.shocktube.mpi_1 .................   Passed  136.22 sec
```

**Pull request merged**
