### PR TITLE
Fix mflux

### PR DESCRIPTION
**Pull request by timteichmann**
## Purpose

Currently the computation of the mass flux ("mflux") in compute_{surf,isurf,boundary} is flawed in two ways:

1. in case surface reactions (exchange or dissociation) are involved the wrong fields of the array are updated as the index is incremented erroneously. This pull request remedies this
2. for {surf,isurf}: Contrary to the descriptions in the code and on the manual the commands currently do not calculate a flux but only the sum of the masses of the impinging DSMC particles. This pull request adds the fluxscale to all computations (like for example in case of the kinetic energy).

## Author(s)

Tim Teichmann (Institute for Technical Physics, Karlsruhe Institute of Technology)

## Backward Compatibility

Yes, since results of the involved computes change

## Implementation Notes

- Commit 1: Do not increment the index if surface reactions are considered in the mass flux
- Commit 2: Scale the mass with the fluxscale (FNUM/A/dt) to obtain the mass flux

## Post Submission Checklist

_Please check the fields below as they are completed_
- [x] The feature or features in this pull request is complete
- [x] Suitable new documentation files and/or updates to the existing docs are included
- [ ] One or more example input decks are included
- [x] The source code follows the SPARTA formatting guidelines

## Further Information, Files, and Links

I think the changes are relatively straightforward. However, please let me know if you would like me to upload a small case to demonstrate the effect of these changes.

NOTE: I can currently not test the KOKKOS version. But I do not expect any issues with them.

### CODE REVIEW

**Comment by aborner1** [comment]
I concur with these changes. I have noticed both issues in the past.

**Comment by stanmoore1** [comment]
@timteichmann I agree with these changes. However, the logic is a little confusing. Can you put the `k++` at the very end so that it uses `k` for all 3 indices instead of `k-1` for the last two?

**Comment by timteichmann** [comment]
Agreed, that makes it much clearer. Should be fine now?

**Review by stanmoore1 — APPROVED** [review]

**Comment by stanmoore1** [comment]
@sjplimp can you take a look at this PR? It looks correct to me.

**Review by sjplimp — APPROVED** [review]

**Comment by sjplimp** [comment]
good catches @timteichmann - thanks!

**Pull request merged**
