### PR TITLE
Enhance functionality of custom attributes for particles, grid cells, and surface elements

### PR DESCRIPTION
**Pull request by sjplimp**
## Purpose

Implement a variety of ways in which custom attributes for particles, grid cells, and surface elements can be more easily and powerfully setup and used by input scripts.  This involved both adding new features and refactoring existing features to be more consistent and usable in other contexts.

In each context custom attributes are single values (vector) or multiple values (array) for each particle, grid cell, or surface element.  The attribute can be integer or floating point.  Each attribute has a "name" so that it can be referenced by other commands.

This is the list of new or altered features.
  
* custom attributes can now be defined for particles, grid cells, and surface elements
* custom surface attributes can be used with non-distributed or distributed surfaces
* new doc page overview section for custom attributes: Section howto 6.17
* read_surf and write_surf options for custom surface attributes
* read_grid and write_grid options for custom grid attributes
* new surf-style variables, which can operate on custom surface attributes
* support for all 3 styles of variables and custom attributes in 3 dump particle/grid/cell commands
* new custom command to create 3 types of custom data and set their values via a variable
* computes and fixes which can handle custom data as input: compute reduce, fix ave/grid, fix ave/surf
* 4 surf_collide style models which specify a temperature can assign the temperature on a per-surf basis via a surf-style variable or custom surf attribute (e.g. read from a data file)
* the surf_react adsorb model now supports distibuted surfs, load balancing, and grid adaptation
* the remove_surf command now has support for distributed surfs
* restart files now support distributed surfs and store custom attribute data for particles, grid cells, and surface elements

## Author(s)

Steve

## Backward Compatibility

Breaks restart backwards compatibility.

## Implementation Notes

_Provide any relevant details about how the changes are implemented, how correctness was verified, how other features - if any - in SPARTA are affected_

## Post Submission Checklist

_Please check the fields below as they are completed_
- [ ] The feature or features in this pull request is complete
- [ ] Suitable new documentation files and/or updates to the existing docs are included
- [ ] One or more example input decks are included
- [ ] The source code follows the SPARTA formatting guidelines

## Further Information, Files, and Links

_Put any additional information here, attach relevant text or image files, and URLs to external sites (e.g. DOIs or webpages)_

### CODE REVIEW

**Comment by sjplimp** [comment]
@stanmoore1 I have made all the updates/changes/testing to this PR that I had planned.  So let me know if there are other issues that arise when regression testing?  Or with respect to Kokkos.

**Comment by stanmoore1** [comment]
@sjplimp this now compiles with Kokkos, but I'm seeing several tests failing with CPU-only (no Kokkos enabled). For the serial (MPI STUBS) case, here is the list:
```
80% tests passed, 13 tests failed out of 66

Total Test time (real) = 158.08 sec

Errors while running CTest
The following tests FAILED:
	  1 - serial.in.ablation.2d (Failed)
	  2 - serial.in.ablation.3d (Failed)
	 27 - serial.in.beam.surf.gs (Failed)
	 28 - serial.in.beam.surf.gs_ps (Failed)
	 29 - serial.in.beam.surf.ps (Failed)
	 30 - serial.in.circle.gs (Failed)
	 31 - serial.in.circle.gs_ps (Failed)
	 32 - serial.in.circle.ps (Failed)
	 37 - serial.in.jagged.2d (Failed)
	 38 - serial.in.jagged.2d.distributed (Failed)
	 58 - serial.in.bfield.grid (Failed)
	 61 - serial.in.sphere.adjust (Failed)
	 62 - serial.in.sphere.constant (Failed)
```

The `/examples/jagged` and `/examples/adjust_temp` inputs failed with an error: ERROR: Incorrect line format in surf file (/sparta/src/read_surf.cpp:937). Other tests failed with numerical differences, not sure if they just need to be reblessed or if it is a true regression.

**Comment by sjplimp** [comment]
I will take a look - thanks

**Comment by stanmoore1** [comment]
Running full regression testing now.

**Pull request merged**
