### PR TITLE
added options for transparent surface elements

### PR DESCRIPTION
**Pull request by sjplimp**
## Purpose

Add option to make sets of surface elements transparent.  I.e. particles just pass thru them,  The purpose is to allow statistics about the flow to be tallied for there surfaces.  New options for these commands: read_surf transparent, surf_collide transparent, compute surf.  Also a new example script in examples/circle.

## Author(s)

Steve

## Backward Compatibility

Shouldn't change existing non-transparent surfs.  But regression testing should be done.

## Implementation Notes

_Provide any relevant details about how the changes are implemented, how correctness was verified, how other features - if any - in SPARTA are affected_

## Post Submission Checklist

_Please check the fields below as they are completed_
- [ ] The feature or features in this pull request is complete
- [ ] Suitable new documentation files and/or updates to the existing docs are included
- [ ] One or more example input decks are included
- [ ] The source code follows the SPARTA formatting guidelines

## Further Information, Files, and Links

_Put any additional information here, attach relevant text or image files, and URLs to external sites (e.g. DOIs or webpages)_

### CODE REVIEW

**Comment by sjplimp** [comment]
@stanmoore1 This may affect Kokkos.  May want to add the new surf_collide transparent model to Kokkos.  The examples/circle/in.circle.transparent script should be added to the regression testing.

**Comment by sjplimp** [comment]
Also, I have a user who wants to try this out. So we should do that before merging into master.

**Comment by stanmoore1** [comment]
This PR needs some Kokkos work, working on it.

**Comment by stanmoore1** [comment]
@sjplimp I merged in the master branch and I getting a compile error:

```
../surf_collide_transparent.h: In member function 'void SPARTA_NS::Surf::add_collide(int, char**)':
../surf.cpp:1879:44: error: invalid new-expression of abstract class type 'SPARTA_NS::SurfCollideTransparent'
         sc[nsc] = new Class(sparta,narg,arg); \
                                            ^
../surf_collide_transparent.h:17:1: note: in expansion of macro 'SurfCollideStyle'
 SurfCollideStyle(transparent,SurfCollideTransparent)
 ^
In file included from ../style_surf_collide.h:4:0,
                 from ../surf.cpp:17:
../surf_collide_transparent.h:29:7: note:   because the following virtual functions are pure within 'SPARTA_NS::SurfCollideTransparent':
 class SurfCollideTransparent : public SurfCollide {
       ^
In file included from ../surf_collide_diffuse.h:24:0,
                 from ../style_surf_collide.h:1,
                 from ../surf.cpp:17:
../surf_collide.h:38:30: note:  virtual SPARTA_NS::Particle::OnePart* SPARTA_NS::SurfCollide::collide(SPARTA_NS::Particle::OnePart*&, double*, double&, int, int&)
   virtual Particle::OnePart *collide(Particle::OnePart *&, double *,
                              ^
../surf.cpp:1894:40: error: invalid new-expression of abstract class type 'SPARTA_NS::SurfCollideTransparent'
     sc[nsc] = new Class(sparta,narg,arg);
                                        ^
../surf_collide_transparent.h:17:1: note: in expansion of macro 'SurfCollideStyle'
 SurfCollideStyle(transparent,SurfCollideTransparent)
 ^
make[1]: *** [surf.o] Error 1
```

**Comment by stanmoore1** [comment]
Regression tests are running.

**Comment by stanmoore1** [comment]
@sjplimp I'm seeing a failure in `examples/sphere/in.sphere.distributed` when running on 4 MPI ranks:

```
ERROR on proc 0: Cell type mis-match when marking on self (../grid.cpp:1359)
```

**Comment by stanmoore1** [comment]
Here is more verbose output:

```
Reading surface file ...
  602 points
  1200 triangles
  -1 1 xlo xhi
  -1 1 ylo yhi
  -1 1 zlo zhi
  0.100631 min triangle edge length
  0.00439601 min triangle area
  440 = cells with surfs
  4260 = total surfs in all grid cells
  22 = max surfs in one grid cell
  0.503156 = min surf-size/cell-size ratio
  0 0 = number of pushed cells
  436 0 = cells overlapping surfs, overlap cells with unmarked corner pts
CELL1 proc 0 icell 1076 id 6170 iface 4 jcell 1046 id 5770 marktype 1 jtype 2
ERROR on proc 0: Cell type mis-match when marking on self (../grid.cpp:1359)
application called MPI_Abort(MPI_COMM_WORLD, 1) - process 0
```

**Comment by stanmoore1** [comment]
Here is Valgrind output:

```
==1614== Invalid read of size 4
==1614==    at 0x571287: SPARTA_NS::Grid::surf2grid_surf_algorithm(int, int) (grid_surf.cpp:566)
==1614==    by 0x5718BC: SPARTA_NS::Grid::surf2grid(int, int) (grid_surf.cpp:66)
==1614==    by 0x5D7A59: SPARTA_NS::ReadSurf::command(int, char**) (read_surf.cpp:206)
==1614==    by 0x57D50A: SPARTA_NS::Input::execute_command() (read_surf.h:17)
==1614==    by 0x57E744: SPARTA_NS::Input::file() (input.cpp:199)
==1614==    by 0x58B3E5: main (main.cpp:30)
==1614==  Address 0x575cfd8 is 2,616 bytes inside a block of size 14,448 free'd
==1614==    at 0x4A06430: free (vg_replace_malloc.c:446)
==1614==    by 0x5D6A82: SPARTA_NS::ReadSurf::read_single(char*) (read_surf.cpp:810)
==1614==    by 0x5D78BC: SPARTA_NS::ReadSurf::command(int, char**) (read_surf.cpp:116)
==1614==    by 0x57D50A: SPARTA_NS::Input::execute_command() (read_surf.h:17)
==1614==    by 0x57E744: SPARTA_NS::Input::file() (input.cpp:199)
==1614==    by 0x58B3E5: main (main.cpp:30)
==1614==
```

**Comment by sjplimp** [comment]
@stanmoore1 OK, I think i fixed this issue with the in.sphere.distributed test

**Comment by stanmoore1** [comment]
Testing this now.

**Comment by stanmoore1** [comment]
I'm seeing Kokkos tests hanging. I'm trying to reproduce this outside of the automated testing.

**Comment by stanmoore1** [comment]
Regression tests are running again.

**Pull request merged**
